version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: web_server
    ports:
      - "80:80"
    networks:
      - app_network
    volumes:
      - ./html:/usr/share/nginx/html:ro  # Serve static files from html directory

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    driver: local
